version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest-asyncio
    versions:
    - 0.15.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: ipdb
    versions:
    - 0.13.5
    - 0.13.6
  - dependency-name: flit
    versions:
    - 3.1.0
  - dependency-name: ipython
    versions:
    - 7.20.0
    - 7.21.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: mypy
    versions:
    - "0.800"
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
  - dependency-name: isort
    versions:
    - 5.7.0
